### PR TITLE
Build a simple API interface

### PR DESCRIPTION
**Pull request by MohannadEhabBarakat**
I have added api.py to simplify the inference code to be done in a few lines. I think this could help people integrate sttyletts2  into their systems more easily. Also, I have added a demo notebook to show how the api works. I have updated the readme.md as well. I have also added 2 more todos I plan to contribute

### CODE REVIEW

**Comment by MohannadEhabBarakat** [comment]
Here is a simple [colab](https://colab.research.google.com/drive/1dKuafNeoMtQdCYOnFWnA-gwwuQOREE4g?usp=sharing) using it

**Comment by fakerybakery** [comment]
I think then this project would have to be GPL licensed due to the phonemizer, no?

**Comment by MohannadEhabBarakat** [comment]
I think that since phonemizer is GPL and is used (but not essential as people are trying new ones and I'm planning on adapting some of them in the future) so the project (the rest of the code) could remain MIT but the phonemizer is GPL. [Like here](https://opensource.stackexchange.com/questions/12064/which-license-for-a-project-combining-mit-libraries-and-gpl-modified-files#:~:text=The%20MIT%20license%20is%20compatible,notices%20of%20all%20parts%20included.)

I'm new to licensing so I'm not sure

**Comment by MohannadEhabBarakat** [comment]
I think this project should be similar to [StyleTTS2](https://github.com/yl4579/StyleTTS2/issues/40) as I built a wrapper around it only

**Comment by fakerybakery** [comment]
It seems to use phonemizer which would make it have to be GPL

**Comment by MohannadEhabBarakat** [comment]
So what is the difference between this project and styletts2? I mean since styletts is MIT couldn't I just use the same analogy to make this MIT?

**Comment by fakerybakery** [comment]
GPL is a "strong copyleft" license which requires all software that even links to it be licensed under the same license and be open sourced. StyleTTS 2, on the other hand, is licensed under the MIT license, a permissive and flexible open source license. If StyleTTS 2 linked to Phonemizer, it would have to be GPL-licensed. This is why the Colab notebooks are separate.

For example, [a fork](https://github.com/neuralvox/styletts2) of StyleTTS 2 links to Phonemizer but is GPL-licensed. This works because MIT is compatible with GPL, but GPL is not compatible with MIT.

**Comment by MohannadEhabBarakat** [comment]
Thanks for the clarification. I got your point I think I'll close this pull request and try to find a way to replicate phonemizer then I'll make a new one. Not sure if I'll be able to do it

**Comment by fakerybakery** [comment]
Yeah, I think replicating phonemizer would be quite hard but I do have a couple of ideas ;) but an API would be great, have you considered releasing your PR as a GPL-licensed fork?

**Comment by MohannadEhabBarakat** [comment]
Yes I'll fix it later today but I don't think it will be mergeable as styletts2 is better with MIT. 

What about instead of replicating phonemizer, generate a dataset of language, text, phoneme. Then use a bert model to translate  language, text -> phoneme. I don't know if this will be easy task or not. But my guess is that it should be relatively easy. Would the resulting model have MIT license?

**Comment by fakerybakery** [comment]
That's an interesting idea! Not sure if you can do text2text w/ BERT though. Also, I ran [an experiment](https://github.com/NeuralVox/OpenPhonemizer) where I trained Deep Phonemizer on espeak, seems to work [relatively well](https://neuralvox.github.io/OpenPhonemizer/).

**Pull request closed without merging**
