### PR TITLE
Add Replicate demo

### PR DESCRIPTION
**Pull request by alaradirik**
Hi,

Thank you for the great work! I implemented a Cog wrapper around StyleTTS 2 and added a demo to [Replicate](https://replicate.com/adirik/styletts2). This pull request makes it possible to run your model inside a Docker environment using [Cog (https://github.com/replicate/cog) and adds a link to the Replicate demo.

I'd also be happy to transfer the Replicate demo to you if you create an organization on Replicate.

Kind regards,
Alara

### CODE REVIEW

**Comment by yl4579** [comment]
I think the output SR is not correct on replicate. Can you fix it before I merge?

**Comment by platform-kit** [comment]
@yl4579 is that why the voice cloning fails in the replicate demo?

**Comment by yl4579** [comment]
@platform-kit I don't know I'm not familiar with replicate and I'm not the author of the demo either. I can see the problem is this line for output: `audio = AudioSegment(audio.data, frame_rate=22050, sample_width=2, channels=1)`, the sr should be 24000 instead.

**Comment by fakerybakery** [comment]
Hi, just a suggestion - do you want to add a note saying that the Replicate demo has more features but will take a minute to start up (I'm thinking of how it takes a couple minutes to start up from Replicate w/ cold boots)? Thanks!

**Pull request closed without merging**
