### PR TITLE
Continued fix of SLM training (see https://github.com/yl4579/StyleTTS2/pull/74)

### PR DESCRIPTION
**Pull request by kmn1024**
1. Move generator related optimizer.steps up, so they won't get zeroed out when 'd_loss_slm != 0'. See https://github.com/yl4579/StyleTTS2/pull/74#issuecomment-1825174074.
2. Tuck all logic related to SLM under 'if slm_out is not None'. @yl4579 Is it normal for `slm_out` to be occasionally None? Is this because my OOD strings are too short? Without this fix, the logging logic after SLM training will occasionally be skipped.

Without fix 1:
```
Epoch [1/20], Step [10/1218], Loss: 0.39906, Disc Loss: 3.80585, Dur Loss: 0.91729, CE Loss: 0.04520, Norm Loss: 0.88187, F0 Loss: 5.34979, LM Loss: 1.75772, Gen Loss: 5.22394, Sty Loss: 0.14641, Diff Loss: 0.72078, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.82867, Mono Loss: 0.07967
Time elasped: 63.88241195678711
Epoch [1/20], Step [20/1218], Loss: 0.40109, Disc Loss: 3.86493, Dur Loss: 0.65782, CE Loss: 0.04811, Norm Loss: 0.92411, F0 Loss: 4.81887, LM Loss: 1.47936, Gen Loss: 5.05884, Sty Loss: 0.12777, Diff Loss: 0.66529, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.85538, Mono Loss: 0.07022
Time elasped: 120.50180172920227
Epoch [1/20], Step [30/1218], Loss: 0.39652, Disc Loss: 3.83995, Dur Loss: 1.33159, CE Loss: 0.05874, Norm Loss: 1.05938, F0 Loss: 7.09664, LM Loss: 1.47302, Gen Loss: 4.94411, Sty Loss: 0.13792, Diff Loss: 0.60246, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.88739, Mono Loss: 0.04210
Time elasped: 182.39928817749023
Epoch [1/20], Step [40/1218], Loss: 0.36586, Disc Loss: 3.73535, Dur Loss: 1.03335, CE Loss: 0.05786, Norm Loss: 0.90980, F0 Loss: 6.04582, LM Loss: 1.65994, Gen Loss: 5.54010, Sty Loss: 0.18344, Diff Loss: 0.81073, DiscLM Loss: 0.25643, GenLM Loss: 0.37330, SLoss: 0.00000, S2S Loss: 0.58883, Mono Loss: 0.08324
Time elasped: 241.64677023887634
Epoch [1/20], Step [50/1218], Loss: 0.39561, Disc Loss: 3.87214, Dur Loss: 1.11643, CE Loss: 0.06730, Norm Loss: 0.80856, F0 Loss: 5.20080, LM Loss: 1.39900, Gen Loss: 4.71890, Sty Loss: 0.13003, Diff Loss: 0.70836, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.95726, Mono Loss: 0.08582
Time elasped: 303.64750480651855
Epoch [1/20], Step [60/1218], Loss: 0.38961, Disc Loss: 3.80765, Dur Loss: 0.93278, CE Loss: 0.04740, Norm Loss: 0.86459, F0 Loss: 5.14459, LM Loss: 1.39974, Gen Loss: 4.78149, Sty Loss: 0.12516, Diff Loss: 0.54093, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.74279, Mono Loss: 0.08246
Time elasped: 362.89968252182007
Epoch [1/20], Step [70/1218], Loss: 0.35986, Disc Loss: 3.88823, Dur Loss: 1.10895, CE Loss: 0.06619, Norm Loss: 0.94683, F0 Loss: 5.25259, LM Loss: 1.39172, Gen Loss: 4.90715, Sty Loss: 0.11738, Diff Loss: 0.74807, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.81517, Mono Loss: 0.09824
Time elasped: 424.3425145149231
Epoch [1/20], Step [80/1218], Loss: 0.34638, Disc Loss: 3.86370, Dur Loss: 0.92268, CE Loss: 0.04954, Norm Loss: 0.88477, F0 Loss: 5.57664, LM Loss: 1.32530, Gen Loss: 4.88593, Sty Loss: 0.12491, Diff Loss: 0.67937, DiscLM Loss: 0.32026, GenLM Loss: 0.55609, SLoss: 0.00000, S2S Loss: 0.72674, Mono Loss: 0.04591
Time elasped: 485.6875464916229
Epoch [1/20], Step [90/1218], Loss: 0.36380, Disc Loss: 3.80194, Dur Loss: 1.38325, CE Loss: 0.06548, Norm Loss: 1.11628, F0 Loss: 5.65351, LM Loss: 1.38777, Gen Loss: 5.12428, Sty Loss: 0.14432, Diff Loss: 0.64102, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.75361, Mono Loss: 0.12854
Time elasped: 544.6129374504089
Epoch [1/20], Step [100/1218], Loss: 0.37162, Disc Loss: 3.72388, Dur Loss: 0.63121, CE Loss: 0.03269, Norm Loss: 0.76734, F0 Loss: 5.07598, LM Loss: 1.67713, Gen Loss: 5.35748, Sty Loss: 0.13136, Diff Loss: 0.61450, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.70641, Mono Loss: 0.07313
Time elasped: 603.7711718082428
Epoch [1/20], Step [110/1218], Loss: 0.38387, Disc Loss: 3.71572, Dur Loss: 0.70806, CE Loss: 0.03327, Norm Loss: 0.81052, F0 Loss: 4.54321, LM Loss: 1.33701, Gen Loss: 5.06492, Sty Loss: 0.12105, Diff Loss: 0.64372, DiscLM Loss: 0.41308, GenLM Loss: 0.46357, SLoss: 0.00000, S2S Loss: 0.45387, Mono Loss: 0.05983
Time elasped: 664.1976268291473
Epoch [1/20], Step [120/1218], Loss: 0.38646, Disc Loss: 3.79432, Dur Loss: 0.73800, CE Loss: 0.03654, Norm Loss: 0.73253, F0 Loss: 4.28007, LM Loss: 1.68789, Gen Loss: 5.11634, Sty Loss: 0.12282, Diff Loss: 0.56682, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.60076, Mono Loss: 0.07191
Time elasped: 723.756754398346
Epoch [1/20], Step [130/1218], Loss: 0.35652, Disc Loss: 3.79281, Dur Loss: 0.82593, CE Loss: 0.03802, Norm Loss: 0.65519, F0 Loss: 3.76569, LM Loss: 1.55788, Gen Loss: 5.29335, Sty Loss: 0.13440, Diff Loss: 0.74076, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.57023, Mono Loss: 0.07216
Time elasped: 782.6303818225861
Epoch [1/20], Step [140/1218], Loss: 0.37963, Disc Loss: 3.73532, Dur Loss: 0.64979, CE Loss: 0.03078, Norm Loss: 0.66758, F0 Loss: 3.47607, LM Loss: 1.60913, Gen Loss: 5.06204, Sty Loss: 0.12592, Diff Loss: 0.63647, DiscLM Loss: 0.22653, GenLM Loss: 0.66188, SLoss: 0.00000, S2S Loss: 0.54364, Mono Loss: 0.06453
Time elasped: 841.5683553218842
Epoch [1/20], Step [150/1218], Loss: 0.36613, Disc Loss: 3.71576, Dur Loss: 0.63693, CE Loss: 0.03173, Norm Loss: 0.77101, F0 Loss: 4.78355, LM Loss: 1.65561, Gen Loss: 5.18247, Sty Loss: 0.11445, Diff Loss: 0.58399, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.61548, Mono Loss: 0.07362
Time elasped: 898.8975949287415
```

With fix 1:
```
Epoch [1/20], Step [10/1218], Loss: 0.40724, Disc Loss: 3.74503, Dur Loss: 1.00301, CE Loss: 0.05052, Norm Loss: 1.00175, F0 Loss: 5.09274, LM Loss: 1.71262, Gen Loss: 5.44997, Sty Loss: 0.17121, Diff Loss: 0.75614, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.85221, Mono Loss: 0.09034 
Time elasped: 64.894611120224  
Epoch [1/20], Step [20/1218], Loss: 0.38132, Disc Loss: 3.83922, Dur Loss: 0.73317, CE Loss: 0.03933, Norm Loss: 0.91726, F0 Loss: 4.54780, LM Loss: 1.40364, Gen Loss: 4.77753, Sty Loss: 0.21270, Diff Loss: 0.73197, DiscLM Loss: 0.54836, GenLM Loss: 0.10720, SLoss: 0.00000, S2S Loss: 0.66763, Mono Loss: 0.05230 
Time elasped: 122.26674699783325
Epoch [1/20], Step [30/1218], Loss: 0.37795, Disc Loss: 3.81702, Dur Loss: 0.74651, CE Loss: 0.03148, Norm Loss: 0.76282, F0 Loss: 3.60241, LM Loss: 1.33165, Gen Loss: 4.69735, Sty Loss: 0.20490, Diff Loss: 0.66204, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.44518, Mono Loss: 0.07578 
Time elasped: 180.7322793006897 
Epoch [1/20], Step [40/1218], Loss: 0.37936, Disc Loss: 3.78111, Dur Loss: 0.70054, CE Loss: 0.03408, Norm Loss: 0.85941, F0 Loss: 4.23952, LM Loss: 1.68848, Gen Loss: 4.98289, Sty Loss: 0.24425, Diff Loss: 0.75123, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.64769, Mono Loss: 0.08142 
Time elasped: 238.10038781166077
Epoch [1/20], Step [50/1218], Loss: 0.36759, Disc Loss: 3.76062, Dur Loss: 0.73471, CE Loss: 0.03444, Norm Loss: 0.82171, F0 Loss: 4.81898, LM Loss: 1.46526, Gen Loss: 4.96719, Sty Loss: 0.20599, Diff Loss: 0.83664, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.64909, Mono Loss: 0.04173 
Time elasped: 296.5684118270874 
Epoch [1/20], Step [60/1218], Loss: 0.38957, Disc Loss: 3.88993, Dur Loss: 0.78310, CE Loss: 0.04457, Norm Loss: 0.79717, F0 Loss: 3.84437, LM Loss: 1.40414, Gen Loss: 4.86061, Sty Loss: 0.21462, Diff Loss: 0.71487, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.76029, Mono Loss: 0.07135 
Time elasped: 354.83180713653564
Epoch [1/20], Step [70/1218], Loss: 0.37135, Disc Loss: 3.89147, Dur Loss: 1.68159, CE Loss: 0.06581, Norm Loss: 0.71542, F0 Loss: 5.11166, LM Loss: 1.31018, Gen Loss: 4.78049, Sty Loss: 0.24813, Diff Loss: 0.80311, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.82581, Mono Loss: 0.10300 
Time elasped: 417.70569491386414
Epoch [1/20], Step [80/1218], Loss: 0.35643, Disc Loss: 3.70478, Dur Loss: 0.95244, CE Loss: 0.04618, Norm Loss: 1.08400, F0 Loss: 5.92208, LM Loss: 1.39194, Gen Loss: 4.99463, Sty Loss: 0.31614, Diff Loss: 0.78999, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.81716, Mono Loss: 0.08532 
Time elasped: 476.74135160446167
Epoch [1/20], Step [90/1218], Loss: 0.36330, Disc Loss: 3.81508, Dur Loss: 0.93145, CE Loss: 0.04728, Norm Loss: 0.80281, F0 Loss: 4.64681, LM Loss: 1.37167, Gen Loss: 4.70892, Sty Loss: 0.30929, Diff Loss: 0.70872, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.78176, Mono Loss: 0.08259 
Time elasped: 538.8548593521118 
Epoch [1/20], Step [100/1218], Loss: 0.37846, Disc Loss: 3.70574, Dur Loss: 0.79586, CE Loss: 0.05672, Norm Loss: 0.84791, F0 Loss: 5.88697, LM Loss: 1.76260, Gen Loss: 5.19837, Sty Loss: 0.28868, Diff Loss: 0.70483, DiscLM Loss: 0.55353, GenLM Loss: 0.21382, SLoss: 0.00000, S2S Loss: 0.75095, Mono Loss: 0.05447
Time elasped: 605.8035960197449
Epoch [1/20], Step [110/1218], Loss: 0.38340, Disc Loss: 3.74452, Dur Loss: 0.73023, CE Loss: 0.03282, Norm Loss: 0.66006, F0 Loss: 3.99223, LM Loss: 1.23754, Gen Loss: 5.06584, Sty Loss: 0.25998, Diff Loss: 0.68356, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.60542, Mono Loss: 0.05584
Time elasped: 666.8061919212341        
Epoch [1/20], Step [120/1218], Loss: 0.37113, Disc Loss: 3.73917, Dur Loss: 0.62328, CE Loss: 0.03091, Norm Loss: 0.69163, F0 Loss: 4.07965, LM Loss: 1.58222, Gen Loss: 5.18706, Sty Loss: 0.24898, Diff Loss: 0.76755, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.59432, Mono Loss: 0.09633
Time elasped: 726.012487411499
Epoch [1/20], Step [130/1218], Loss: 0.34721, Disc Loss: 3.70550, Dur Loss: 0.87134, CE Loss: 0.04122, Norm Loss: 0.87697, F0 Loss: 5.37541, LM Loss: 1.65681, Gen Loss: 5.08771, Sty Loss: 0.24324, Diff Loss: 0.72992, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.58182, Mono Loss: 0.10374
Time elasped: 788.111878156662
Epoch [1/20], Step [140/1218], Loss: 0.37339, Disc Loss: 3.86153, Dur Loss: 0.71377, CE Loss: 0.03255, Norm Loss: 0.84450, F0 Loss: 4.75012, LM Loss: 1.66162, Gen Loss: 4.94090, Sty Loss: 0.24055, Diff Loss: 0.70908, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.54615, Mono Loss: 0.08908
Time elasped: 847.782068490982
Epoch [1/20], Step [150/1218], Loss: 0.38153, Disc Loss: 3.82138, Dur Loss: 0.73931, CE Loss: 0.03436, Norm Loss: 0.66352, F0 Loss: 2.88641, LM Loss: 1.54591, Gen Loss: 5.19642, Sty Loss: 0.24517, Diff Loss: 0.74890, DiscLM Loss: 0.00000, GenLM Loss: 0.00000, SLoss: 0.00000, S2S Loss: 0.57637, Mono Loss: 0.06705
Time elasped: 908.8858561515808
```

### CODE REVIEW

**Comment by yl4579** [comment]
I guess it's skipped too often. Out of 15 lines you printed it seems only two are not None. But as long as it runs I think it should be fine.

**Comment by yl4579** [comment]
I have fixed some other issues. I think I have to test this code now on my end to make sure it produces the correct output.

**Comment by kmn1024** [comment]
> I guess it's skipped too often. Out of 15 lines you printed it seems only two are not None. But as long as it runs I think it should be fine.

What's the likely cause of this? I can't figure out the meaning of https://github.com/yl4579/StyleTTS2/blob/main/Modules/slmadv.py#L129...

**Comment by yl4579** [comment]
The run cannot be completed if the batch size is less than 1 because of some squeeze operation.

**Comment by kmn1024** [comment]
The `slmadv_params.min_len(=400)` `slmadv_params.max_len(=500)` range is too tight. Decreasing `slmadv_params.min_len` to 200 reduces the frequency of `slm_out is None` to almost 0 (I'm just using the standard `Data/OOD_texts.txt`).

**Comment by yl4579** [comment]
These were default on 4 A100 GPUs.

**Pull request merged**
