### PR TITLE
Add importables + Gradio GUI

### PR DESCRIPTION
**Pull request by fakerybakery**
Please see updated README for details. Requested by multiple people.

Note: I will be updating the HF space more often since I have direct push access, but I'll try to make PRs occasionally to keep it up-to-date

> ## Python API
> 
> You can now use StyleTTS 2 directly in your programs! A `pip`-compatible package is coming soon.
> 
> Multi-Speaker Inference:
> 
> ```python
> from scipy.io.wavfile import write
> import msinference
> text = 'Hello world!'
> voice = msinference.compute_style('voice.wav')
> wav = msinference.inference(text, voice, alpha=0.3, beta=0.7, diffusion_steps=7, embedding_scale=1)
> write('result.wav', 24000, wav)
> ```
> 
> LJSpeech Inference:
> 
> ```python
> from scipy.io.wavfile import write
> import ljinference
> text = 'Hello world!'
> noise = torch.randn(1,1,256).to('cuda' if torch.cuda.is_available() else 'cpu')
> wav = ljinference.inference(text, noise, diffusion_steps=7, embedding_scale=1)
> write('result.wav', 24000, wav)
> ```
> 
> For longer text, you can [help implement #54](https://github.com/yl4579/StyleTTS2/issues/54) or use Tortoise TTS for splitting:
> 
> ```python
> from tortoise.utils.text import split_and_recombine_text
> import numpy as np
> from scipy.io.wavfile import write
> import msinference
> text = 'Long text here...'
> texts = split_and_recombine_text(text)
> audios = []
> voice = msinference.compute_style('voice.wav')
> for t in progress.tqdm(texts):
>     audios.append(styletts2importable.inference(t, voice, alpha=0.3, beta=0.7, diffusion_steps=7, embedding_scale=1))
> write('result.wav', 24000, np.concatenate(audios))
> ```
> 
> ## GUI
> 
> You can run inference (finetuning coming soon) on a GUI based on the [online demo](https://huggingface.co/spaces/styletts2/styletts2) powered by Gradio.
> 
> ```bash
> python app.py
> ```
> 
> **NOTE: Only the multi-speaker tab supports long-text currently.**
> 
> Note: the online demo will be updated more frequently as changes are pushed directly to it (rather than through PRs). If you would like to use the latest (potentially unstable) version, use Docker:
> 
> ```bash
> docker run -it -p 7860:7860 --platform=linux/amd64 --gpus all registry.hf.space/styletts2-styletts2:latest python app.py
> ``

### CODE REVIEW

**Comment by yl4579** [comment]
I just found this PR contains phonemizer, so it will make this repo non-MIT. I'm not sure if this is okay or would it be better to make a new repo and I can add it to the README instead?

**Comment by fakerybakery** [comment]
Yeah, I would hate this repo to be non-MIT. How about I'll maintain a fork and try to keep it synced, and can you link to the fork? I'll add you as a contributor to the fork. Is that ok?

**Comment by yl4579** [comment]
I think I can add a link to the package and let the users decide whether to install it or not.

**Comment by fakerybakery** [comment]
OK! I'm going to start maintaining [this fork](https://github.com/neuralvox/styletts2) instead. I'll add you as a contributor.

**Comment by fakerybakery** [comment]
@yl4579 Are you OK if I leave out the former MIT license text, since the GitHub license detector only detects it if it only has the GPL text?

**Comment by lxe** [comment]
> I just found this PR contains phonemizer, so it will make this repo non-MIT. I'm not sure if this is okay or would it be better to make a new repo and I can add it to the README instead?

This project itself depends on `phonemizer` library, even without this change.

**Pull request closed without merging**
